=== MGReyes/Base_Datos/Lab4/ClientesEmpresa.dtd
<!DOCTYPE ClientesEmpresa [
    <!ELEMENT ClientesEmpresa (Cliente+)>
    <!ELEMENT Cliente (Razon_Social, Zona, Vendedor, Maquina*, Telefono*)>
    <!ATTLIST Cliente Cuit ID #REQUIRED>
    <!ELEMENT Razon_Social(#PCDATA)>
    <!ELEMENT Zona (#PCDATA)>
    <!ELEMENT Vendedor (Nombre, Apellido)>
    <!ATTLIST Vendedor Cuil ID #REQUIRED>
    <!ELEMENT Nombre (#PCDATA)>
    <!ELEMENT Apellido (#PCDATA)>
    <!ELEMENT Maquina (Marca, Modelo)>
    <!ATTLIST Maquina Id_Maquina ID #REQUIRED>
    <!ELEMENT Marca (#PCDATA)>
    <!ELEMENT Modelo (#PCDATA)>
    <!ELEMENT Telefono (#PCDATA)>
]>

=== MGReyes/Base_Datos/Lab4/clientes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ClientesEmpresa
PUBLIC "SYSTEM"
       "ClientesEmpresa.dtd">
<ClientesEmpresa>
 <Cliente Cuit="21857959152">
  <Razon_Social>Erat Consulting</Razon_Social>
  <Zona>Interior</Zona>
  <Vendedor Cuil="20675821714">
   <Nombre>Aurora</Nombre>
   <Apellido>Dalton</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="20">
   <Marca>Elit A Feugiat Incor</Marca>
   <Modelo>KV163l</Modelo>
  </Maquina>
  <Telefono>4959217</Telefono>
 </Cliente>
 <Cliente Cuit="46690258622">
  <Razon_Social>Nisi Dictum LLC</Razon_Social>
  <Zona>Interior</Zona>
  <Vendedor Cuil="34419713737">
   <Nombre>Zeph</Nombre>
   <Apellido>Stark</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="8">
   <Marca>Cras Convallis Conva</Marca>
   <Modelo>KM388d</Modelo>
  </Maquina>
  <Telefono>4123348</Telefono>
  <Telefono>4544345</Telefono>
  <Telefono>4775479</Telefono>
  <Telefono>4860944</Telefono>
 </Cliente>
 <Cliente Cuit="47157018047">
  <Razon_Social>Elit Foundation</Razon_Social>
  <Zona>Interior</Zona>
  <Vendedor Cuil="31576877022">
   <Nombre>Yoshio</Nombre>
   <Apellido>Ewing</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="10">
   <Marca>Diam Institute</Marca>
   <Modelo>NO991f</Modelo>
  </Maquina>
 </Cliente>
 <Cliente Cuit="20733797847">
  <Razon_Social>Donec Luctus Company</Razon_Social>
  <Zona>Interior</Zona>
  <Vendedor Cuil="39728412060">
   <Nombre>Ira</Nombre>
   <Apellido>Bonner</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="1">
   <Marca>A Incorporated</Marca>
   <Modelo>JA689p</Modelo>
  </Maquina>
  <Maquina ID_Maquina="7">
   <Marca>Consequat Corporatio</Marca>
   <Modelo>ZT202a</Modelo>
  </Maquina>
  <Telefono>4132621</Telefono>
  <Telefono>4398950</Telefono>
 </Cliente>
 <Cliente Cuit="37634697973">
  <Razon_Social>Feugiat Sed Corporation</Razon_Social>
  <Zona>Interior</Zona>
  <Vendedor Cuil="20675821714">
   <Nombre>Aurora</Nombre>
   <Apellido>Dalton</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="27">
   <Marca>Fusce Fermentum Indu</Marca>
   <Modelo>QI218i</Modelo>
  </Maquina>
  <Telefono>4683103</Telefono>
 </Cliente>
 <Cliente Cuit="44492424700">
  <Razon_Social>In Ornare Sagittis Corporation</Razon_Social>
  <Zona>Interior</Zona>
  <Vendedor Cuil="22057905057">
   <Nombre>Calista</Nombre>
   <Apellido>Ratliff</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="21">
   <Marca>Elit Erat Vitae Indu</Marca>
   <Modelo>TG910a</Modelo>
  </Maquina>
  <Telefono>4049355</Telefono>
 </Cliente>
 <Cliente Cuit="41168483062">
  <Razon_Social>Metus Eu Erat Foundation</Razon_Social>
  <Zona>Noreste</Zona>
  <Vendedor Cuil="21588486935">
   <Nombre>Silas</Nombre>
   <Apellido>Avila</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="7">
   <Marca>Consequat Corporatio</Marca>
   <Modelo>ZT202a</Modelo>
  </Maquina>
  <Telefono>4146262</Telefono>
  <Telefono>4390010</Telefono>
 </Cliente>
 <Cliente Cuit="42381513522">
  <Razon_Social>Sagittis Felis Donec Institute</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="20675821714">
   <Nombre>Aurora</Nombre>
   <Apellido>Dalton</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="22">
   <Marca>Elit Etiam Laoreet I</Marca>
   <Modelo>XM629y</Modelo>
  </Maquina>
  <Telefono>4205161</Telefono>
  <Telefono>4264954</Telefono>
  <Telefono>4954749</Telefono>
 </Cliente>
 <Cliente Cuit="46430152934">
  <Razon_Social>Ad Litora Consulting</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="26038334742">
   <Nombre>Emery</Nombre>
   <Apellido>Gilbert</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="7">
   <Marca>Consequat Corporatio</Marca>
   <Modelo>ZT202a</Modelo>
  </Maquina>
  <Telefono>4587599</Telefono>
  <Telefono>4827946</Telefono>
 </Cliente>
 <Cliente Cuit="48194781422">
  <Razon_Social>Risus Corporation</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="26301106493">
   <Nombre>Oren</Nombre>
   <Apellido>Koch</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="14">
   <Marca>Donec LLP</Marca>
   <Modelo>SV475o</Modelo>
  </Maquina>
  <Telefono>4575118</Telefono>
 </Cliente>
 <Cliente Cuit="24575097766">
  <Razon_Social>Vitae Odio Corp.</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="34419713737">
   <Nombre>Zeph</Nombre>
   <Apellido>Stark</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="14">
   <Marca>Donec LLP</Marca>
   <Modelo>SV475o</Modelo>
  </Maquina>
  <Telefono>4286350</Telefono>
  <Telefono>4610846</Telefono>
 </Cliente>
 <Cliente Cuit="48978380447">
  <Razon_Social>Ipsum Sodales Associates</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="23140188679">
   <Nombre>John</Nombre>
   <Apellido>Watkins</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="15">
   <Marca>Duis Gravida Praesen</Marca>
   <Modelo>BO367l</Modelo>
  </Maquina>
  <Maquina ID_Maquina="22">
   <Marca>Elit Etiam Laoreet I</Marca>
   <Modelo>XM629y</Modelo>
  </Maquina>
 </Cliente>
 <Cliente Cuit="25224345014">
  <Razon_Social>Et Magnis Dis PC</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="29685802720">
   <Nombre>Charity</Nombre>
   <Apellido>Silva</Apellido>
  </Vendedor>
 </Cliente>
 <Cliente Cuit="37395045887">
  <Razon_Social>Ligula Aliquam Corporation</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="27980914786">
   <Nombre>Mira</Nombre>
   <Apellido>Simmons</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="16">
   <Marca>Egestas Aliquam Asso</Marca>
   <Modelo>CV085k</Modelo>
  </Maquina>
 </Cliente>
 <Cliente Cuit="37842910105">
  <Razon_Social>Erat Associates</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="26048204535">
   <Nombre>Penelope</Nombre>
   <Apellido>Mcleod</Apellido>
  </Vendedor>
  <Telefono>4274071</Telefono>
 </Cliente>
 <Cliente Cuit="38421805343">
  <Razon_Social>Sit Amet Nulla Inc.</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="21020908281">
   <Nombre>Serina</Nombre>
   <Apellido>Love</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="30">
   <Marca>Justo LLC</Marca>
   <Modelo>RR799m</Modelo>
  </Maquina>
  <Telefono>4242845</Telefono>
  <Telefono>4567018</Telefono>
  <Telefono>4786051</Telefono>
  <Telefono>4817287</Telefono>
  <Telefono>4918122</Telefono>
 </Cliente>
 <Cliente Cuit="38817149425">
  <Razon_Social>Duis LLC</Razon_Social>
  <Zona>Pampa</Zona>
  <Vendedor Cuil="26213114093">
   <Nombre>Jin</Nombre>
   <Apellido>Terrell</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="28">
   <Marca>In Consulting</Marca>
   <Modelo>IB182k</Modelo>
  </Maquina>
  <Telefono>4329048</Telefono>
  <Telefono>4425304</Telefono>
 </Cliente>
 <Cliente Cuit="20964881694">
  <Razon_Social>Luctus Lobortis Class LLC</Razon_Social>
  <Zona>Patagonia</Zona>
  <Vendedor Cuil="33445206834">
   <Nombre>Yuli</Nombre>
   <Apellido>Little</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="9">
   <Marca>Cursus Integer Molli</Marca>
   <Modelo>KU431w</Modelo>
  </Maquina>
  <Telefono>4049621</Telefono>
  <Telefono>4341290</Telefono>
  <Telefono>4510024</Telefono>
 </Cliente>
 <Cliente Cuit="40054868870">
  <Razon_Social>Malesuada Integer Id Associate</Razon_Social>
  <Zona>Patagonia</Zona>
  <Vendedor Cuil="39942457508">
   <Nombre>Jade</Nombre>
   <Apellido>Coffey</Apellido>
  </Vendedor>
 </Cliente>
 <Cliente Cuit="45206904390">
  <Razon_Social>Sed Tortor Institute</Razon_Social>
  <Zona>Patagonia</Zona>
  <Vendedor Cuil="23661966184">
   <Nombre>Wynter</Nombre>
   <Apellido>Bush</Apellido>
  </Vendedor>
  <Maquina ID_Maquina="7">
   <Marca>Consequat Corporatio</Marca>
   <Modelo>ZT202a</Modelo>
  </Maquina>
  <Maquina ID_Maquina="13">
   <Marca>Dolor Tempus Inc.</Marca>
   <Modelo>BW952q</Modelo>
  </Maquina>
 </Cliente>
</ClientesEmpresa>
